### ISSUE TITLE
Section specific numbering

### ISSUE THREAD

**Issue by cpsievert** [adletaw/captioner#11]
Hi @adletaw,

@hadley and I are interested in using this package for https://github.com/hadley/ggplot2-book/

I'm interested in achieving section specific numbering using this framework. For instance, the fifth figure within the third section should be cited as Figure 3.5. One idea I had to add support for this would be to increment the section counter whenever `#` appears at the beginning of a line in the source Rmd file.

Unfortunately, we render each section separately, so that solution wouldn't work in that case, but a reasonable workaround is to manually add the section specific prefix, like this:

```s
# Put me at the beginning of the 2nd section
ref <- list(
  fig = pryr::partial(captioner::captioner, prefix = "Figure 2.")(),
  tbl = pryr::partial(captioner::captioner, prefix = "Table 2.")()
)
ref$fig("iris", caption = "Iris Data")
#> [1] "Figure 2. 1: Iris Data"
ref$fig("mtcars", caption = "Mtcars Data")
#> [1] "Figure 2. 2: Mtcars Data"
ref$tbl("numbers", caption = "A table of numbers")
#> [1] "Table 2. 1: A table of numbers"
```

For this reason, it'd be great if you could remove the space [here](https://github.com/adletaw/captioner/blob/master/captioner/R/captioner.R#L84) and [here](https://github.com/adletaw/captioner/blob/master/captioner/R/captioner.R#L87) and switch the default prefix from "Figure" to "Figure ". Thanks!

**Comment by adletaw** [comment]
Hi @cpsievert!

Cool!  You are getting at a more general problem that also comes up if you want to do something like "Figure 1a, Figure 1b...."  Ultimately, I'd like to add some way to deal with that within captioner - but haven't had much time to think about it yet.  Anyways, I'm happy to adjust the spacing to support your workaround for now.

**Comment by adletaw** [comment]
What I did for now is add another parameter to the `captioner` function called `auto_space`.  If you set this to `F` when you generate your function, the problem will be fixed.  I have in mind a few ways to do hierarchical numbering though.  I'll take a look now that I know someone is interested.

**Comment by cpsievert** [comment]
Awesome, thanks, keep up the good work!
