### ISSUE TITLE
LaTeX mode

### ISSUE THREAD

**Issue by krlmlr** [adletaw/captioner#13]
May I suggest a "LaTeX mode" that uses `\caption{}` and `\ref{}` (or `\Cref`/`\cref`) constructs? In Markdown mode (the current default), a document output hook (#6) could also look for `\ref{}` markup in the text and replace it by the corresponding references.

Use case: Conversion to LaTeX (via pandoc) and using LaTeX's caption feature. I'd be happy to contribute.

Thanks for your package, it is a very nice and clean solution for a missing feature in Markdown.

**Comment by adletaw** [comment]
Hello @krlmlr , thanks for your interest!  Maybe you could elaborate on why this would be needed in LaTeX?  R/Markdown doesn't have a pre-existing method for numbering captions, but LaTeX does and it works well for numbering figures - even when using Sweave to create them.  Am I missing something?

I'm glad you are enjoying the package!

**Comment by krlmlr** [comment]
Use case (extended): Creation of both LaTeX and HTML output from the same source, with minimal (if any) modifications.

**Comment by benmarwick** [comment]
+1 excellent request, would extend the potential of this package substantially!

**Comment by adletaw** [comment]
*captioner* is no longer being developed.  Check out [bookdown](https://github.com/rstudio/bookdown) for captioning with markdown.
