### ISSUE TITLE
Forward references

### ISSUE THREAD

**Issue by krlmlr** [adletaw/captioner#14]
Currently, it looks like the references are numbered by order of appearance; this contrasts with LaTeX's numbering by order of *definition*. Is this behavior desired?

**Comment by adletaw** [comment]
You are right - it might be nice to have a way to define captions ahead of time in order to mess with the numbering.  I'll look into adding that.

**Comment by adletaw** [comment]
Fixed in [version 2.2.0](https://github.com/adletaw/captioner/releases/tag/v2.2.0)

**Comment by krlmlr** [comment]
Thanks for your quick response. This is a big step forward, but you still need to declare the captions (or at least the labels) beforehand. Is there a warning if figures don't appear in order of declaration?

Originally, I thought it's possible to use the `document` hook (#6) for this: Write something like `\Cref{...}` into the document (where `...` is something that is really unique, e.g. the label *and* its SHA1 hash), and fix the numbering only when the entire document is finished.
