### ISSUE TITLE
Feature requests: Keep caption with figure/table; spacing control

### ISSUE THREAD

**Issue by eipi10** [adletaw/captioner#18]
I stumbled across `captioner` while trying to figure out how to put captions above figures when using `rmarkdown` with conversion to PDF. I assume there must be a way to force the caption to be above the figure in `Latex`, but my `Latex` knowledge is limited, and I couldn't find a way that worked in my `rmarkdown` document. `captioner` makes it easy to put the caption above the figure and to cross-reference figures in the main text.
In the process of writing and coding my document, I became aware of two additional features that would be nice to have in `captioner`. First, I'd like to find a way to force the caption to stay with the figure, so that there won't be a page break between the caption and the figure. For now, I've had use hard page breaks (`\newpage`) before the caption in cases where there's a bad page break. I assume there's some way to anchor the caption to the figure, but my knowledge of `knitr` and `Latex` is still too rudimentary to work out how to do it.
Second, I'd like to be able to control the amount of vertical space between the caption and the figure. I tried, for example, `\vspace{3 mm}` between caption and figure, but the PDF is rendered with too much vertical space between caption and figure, regardless of what `vspace` value I choose. It would be nice to have finer control over vertical spacing within `captioner`, though I realize this may once again be an issue of just knowing how to properly insert the right `Latex` command in the document.

**Comment by adletaw** [comment]
Hm.. I still haven't decided how much typesetting should be a part of captioner.  My gut feeling is that this role should belong to other packages focused on that.  But I may change my mind some day.  Unfortunately, I am very busy with other projects these days, so if that can of beans is opened, it probably wont be soon. 

You are right that it would be extremely convenient for the captions to be attached to the figures in some way.  Unfortunately, that is a major feature change so... probably wont come soon :disappointed: Luckily for you, LaTeX is a beautiful, highly configurable (admittedly with some pain) piece of software with which you can totally solve all of your formatting problems.

Sorry for this very noncommittal answer, but thank you for your interest in `captioner` :smile:  I really am planning to work on some of these things, just probably not on the time scale you would want.

**Comment by eipi10** [comment]
Learning a minimally adequate amount of LaTeX is on my to do list. For now, `captioner` plus a few kludges gets me most of the way there. Thanks for your response and for creating and sharing the `captioner` package.

**Comment by adletaw** [comment]
See also #13

**Comment by adletaw** [comment]
*captioner* is no longer being developed.  Check out [bookdown](https://github.com/rstudio/bookdown) for captioning with markdown.
