### ISSUE TITLE
knitr cache with captions.

### ISSUE THREAD

**Issue by dill** [adletaw/captioner#22]
Given the `knitr` document below, running:
```
rmarkdown::render("knit_example.Rmd","html_document")
```
once gives the correct output (figure caption works fine). Editing the document and re-running the call to `render` gives just "Figure 1:" and no caption. Setting `opts_chunk$set(cache=FALSE)` gives the correct caption every time.

Not sure if this behaviour is expected, I am setting up my document incorrectly or this is a bug. Any advice would be gratefully received.

    ---
    title: '`knitr` cache with `captioner`'
    ---

    This is a test.

    ```{r echo=FALSE}
    library(knitr)
    library(captioner)

    # make a numbering for figures
    fig_nums <- captioner(prefix="Figure")

    opts_chunk$set(cache=FALSE)
    ```

    ```{r echo=FALSE}
    fig_nums(name="fig1", caption="a caption", display=FALSE)
    ```

    The below code generates `r fig_nums("fig1", display = "cite")`.

    ```{r fig1, fig.cap="", fig.height=4}
    plot(rnorm(10), rnorm(10))
    ```

    `r fig_nums("fig1")`

**Comment by adletaw** [comment]
Hello @dill 

Thanks for the great example!  You seem to have found the source of the problem already (`cache`) but I'm not sure why this is happening to you.  [By default, `cache = FALSE`](http://yihui.name/knitr/options/).  In fact, I wasn't able to reproduce your problem without setting `cache = TRUE` first.

That aside, I'm not sure this really IS the desired `captioner` behavior.  Ideally, those captions would be stored along with the rest of the code chunk.  I am going to have to take a closer look at the inner workings of the `cache` option to see if I can understand why that is happening and whether there is an easy way to fix it.

Weird problem!

**Comment by dill** [comment]
Sorry there was a typo in that original code sample and it should be `cache=TRUE` -- there are no problems when `cache=FALSE`.

Apologies for any confusion caused!

**Comment by adletaw** [comment]
@dill Are you still having problems with this?  I haven't been able to replicate the bug with either `cache=TRUE` or `cache=FALSE`

**Comment by dill** [comment]
Sorry for the delay... This seems to work now! Thanks!
