### ISSUE TITLE
caption numbering order

### ISSUE THREAD

**Issue by e-sr** [adletaw/captioner#25]
Hi @adletaw,

thank you for the captioner pakage. I have two remarks on it: 

- i find a limitation the order  which numbering occour. As in your example the output is 
```{r}
fig_nums("snuff",  display = "cite")
#> [1] "Figure  1"
fig_nums("bounce", "Bounce height (cm) of balls made of various types of rubber.")
#> [1] "Figure  2: Bounce height (cm) of balls made of various types of rubber."
fig_nums("snuff",  "Average size of snuff boxes used from 1808 to 1908.")
#> [1] "Figure  1: Average size of snuff boxes used from 1808 to 1908."
fig_nums("bounce", display = "cite")
#> [1] "Figure  2"
```

I find that an inverse numbering (snuff 2 and bounce 1) would be more useful as  the numbering will be the same as the display order of figures in the document  (if you define the caption where the image are printed out in the documents.)

- Anoter  point is that  captions without captions content should give a warning.

**Comment by adletaw** [comment]
Hello, and thank you for your interest!  I'm just letting you know that development of `captioner` is on hold at the moment while I finish my PhD thesis.  I'll hopefully be taking a look at this in the near future though.

**Comment by adletaw** [comment]
Hello @e-sr 

The numbering order was intentional.  You can pre-define the captions in order to get the numbering correct (since there is a `display = F` option).  That said, I may add an option to the `captioner` function to modify the default numbering behavior.

Your comment on warnings has been noted in #19.

**Comment by adletaw** [comment]
@e-sr The logic on ordering is that you would normally be citing figures in the order of display, i.e., you wouldn't cite `Figure 2` before `Figure 1`.  Therefore it makes sense to number them in the order referenced.  I added the `display = F` option to allow you to mess with that numbering order if needed.  Still, you are right that it might be a good idea to add some option for manipulating the numbering for ease of use.

**Comment by adletaw** [comment]
*captioner* is no longer being developed.  Check out [bookdown](https://github.com/rstudio/bookdown) for captioning with markdown.
