### ISSUE TITLE
Similar functionality in bookdown

### ISSUE THREAD

**Issue by yihui** [adletaw/captioner#29]
Hi, I just want to bring the bookdown package to your attention (you probably have noticed it): https://github.com/rstudio/bookdown Figure/table caption numbering is one of the many issues that bookdown has addressed, and you may find more info about it from Chapter 2 in the doc: https://bookdown.org/yihui/bookdown/ The functionality can be applied to any Rmd documents.

**Comment by adletaw** [comment]
Hello @yihui,

I sure have noticed it!  I have stopped developing `captioner` thanks to bookdown, but I'll put a note on the README directing people that way.
