### ISSUE TITLE
Appendix citations

### ISSUE THREAD

**Issue by rpietro** [adletaw/captioner#31]
First of all, I absolutely love captioner, and use it literally every day. I recently came across a case that I don't how to handle, though. Specifically, when citing tables in an Appendix, the numbering system usually has to change to something like A1, A2, etc.

Is there a way to get that done with captioner?

thanks

**Comment by adletaw** [comment]
Hello @rpietro ,

I'm glad you are getting some use out of captioner!  There is a way to do that.  You just have to change the `prefix` when you are defining your captioning function.  For example:

```{r}
append -> captioner(prefix = "Figure A", auto_space = FALSE)
```
The `auto_space` parameter will prevent captioner from adding an additional space between "A" and the number.  If you have an appendix B, you could do the same thing using `prefix = "Figure B"` and so on...

**Comment by rpietro** [comment]
thanks a ton
