### ISSUE TITLE
A recognized license would help re-packaging/distributing captioner

### ISSUE THREAD

**Issue by tfenne** [adletaw/captioner#34]
Hi!  I'm trying to get a recipe for captioner into conda-forge so that it can be installed via conda, and used as a dependency in other conda packages.  One potential problem with that is that there is no real license (just a copyright statement/assertion) for captioner.

I'm not trying to lobby for any particular license, but it would be great if a recognized license was used for the package, e.g. MIT, GPL, BSD, any of the Creative Commons licenses, etc.  Any chance you'd be willing to update?  If so I could submit a PR with a new LICENSE file and add license statements to the top of files so as to make it little to no work for you...

**Comment by benmarwick** [comment]
Now we have a file with the full text of the license. Do you really need license statements at the top of all files? This is not typical among R packages, e.g. https://github.com/tidyverse/ggplot2

**Comment by tfenne** [comment]
Thanks @benmarwick.  I don't think it's necessary to have license statements in every file - some projects (particularly in other languages) choose to do this to make it crystal clear that each file is covered under the license, but I think simply having a license file is sufficient.

Thanks again!

**Comment by benmarwick** [comment]
Righto, thanks! Ok to close this then, I think

**Comment by tfenne** [comment]
Cheers!
