### ISSUE TITLE
caption formatting

### ISSUE THREAD

**Issue by adletaw** [adletaw/captioner#7]
figure out ways to improve the formatting (look) of the captions.  for example, they shouldn't span the whole width of the page.

**Comment by andrewdolman** [comment]
Would be good to be able to have sub and superscript characters too. Using either markdown, N~2~, or N[2].

**Comment by adletaw** [comment]
That sounds like a good idea in theory- Could you give in example of how that would be used?

**Comment by andrewdolman** [comment]
Actually, it already does work just fine! Not sure why I thought it didn't - must have been doing something else wrong. 

```
table_nums <- captioner(prefix = "Table")
table_nums(name = "phys", caption = "N~2~ fixation rates.")
table_nums("phys")
```

**Comment by adletaw** [comment]
See #23, #6, #13
